AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    394f58fb-15e3-4baf-97af-94d8db09bf71:
      size:
        width: 60
        height: 60
      position:
        x: 500
        'y': 130
      z: 0
      embeds: []
    73d34642-3944-44c6-ac8e-2d7a482c2f2d:
      size:
        width: 60
        height: 60
      position:
        x: 340
        'y': 130
      z: 0
      embeds: []
    eee258e0-9c6e-411a-b761-2902f4c58fe5:
      source:
        id: c90408b2-839d-4766-b642-7bb0d4b1756f
      target:
        id: 73d34642-3944-44c6-ac8e-2d7a482c2f2d
      z: 1
    370192c5-ed0e-4c43-a97c-42b2ebb63a59:
      size:
        width: 60
        height: 60
      position:
        x: 680
        'y': 130
      z: 0
      embeds: []
Resources:
  IAMRoleCodePipeline:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                Effect: Allow
              - Action:
                  - 's3:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'
                Effect: Allow
            Version: 2012-10-17
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 394f58fb-15e3-4baf-97af-94d8db09bf71
  S3BucketPipeline:
    Type: 'AWS::S3::Bucket'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 73d34642-3944-44c6-ac8e-2d7a482c2f2d
  S3BucketOutput:
    Type: 'AWS::S3::Bucket'
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref S3BucketPipeline
      RoleArn: !GetAtt IAMRoleCodePipeline.Arn
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifacts
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Deploy
          Actions:
          - Name: Artifact
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: S3
            InputArtifacts:
            - Name: SourceArtifacts 
            OutputArtifacts: []
            Configuration:
              BucketName: !Ref S3BucketOutput
              Extract: 'false'
              ObjectKey: tempcodepipeline22
            RunOrder: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 370192c5-ed0e-4c43-a97c-42b2ebb63a59

Parameters:
  GitHubUser:
    Type: String
    Description: GitHub User
    Default: stelligent
  GitHubRepo:
    Type: String
    Description: GitHub Repo to pull from. Only the Name. not the URL
    Default: devops-essentials
  GitHubBranch:
    Type: String
    Description: GitHub Branch
    Default: master
  GitHubToken:
    NoEcho: true
    Type: String
    Description: Secret

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${CodePipeline}
    Description: CodePipeline URL